# Generated by Django 5.2.15 on 2026-07-20 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='One goal per user. References Core service user.', unique=True)),
                ('target_weight', models.FloatField(help_text='Target body weight in kilograms.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(500.0)])),
                ('target_date', models.DateField(blank=True, help_text='Target date to achieve the goal (optional).', null=True)),
                ('target_body_fat', models.FloatField(blank=True, help_text='Target body fat percentage (optional).', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this goal was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this goal was last updated.')),
            ],
            options={
                'verbose_name': 'User Goal',
                'verbose_name_plural': 'User Goals',
                'db_table': 'team2_user_goal',
            },
        ),
        migrations.CreateModel(
            name='PhysicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='References the user in Core service. Not a FK (cross-service).')),
                ('weight', models.FloatField(help_text='Body weight in kilograms.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(500.0)])),
                ('height', models.FloatField(help_text='Height in centimeters.', validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(300.0)])),
                ('bmi', models.FloatField(editable=False, help_text='Body Mass Index, auto-calculated from weight and height.')),
                ('body_fat_percentage', models.FloatField(blank=True, help_text='Body fat percentage (optional).', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)])),
                ('muscle_mass', models.FloatField(blank=True, help_text='Muscle mass in kilograms (optional).', null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('notes', models.TextField(blank=True, default='', help_text='Optional free-text notes for this record.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. Records are never physically removed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
            ],
            options={
                'verbose_name': 'Physical Record',
                'verbose_name_plural': 'Physical Records',
                'db_table': 'team2_physical_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_deleted'], name='idx_physical_user_active'), models.Index(fields=['user_id', '-created_at'], name='idx_physical_user_date')],
            },
        ),
    ]
