# Generated by Django 5.2.15 on 2026-07-20 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='One settings row per user.', unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Master switch — if False, no notifications are sent to this user.')),
                ('quiet_hours_start', models.TimeField(default='22:00', help_text='Start of quiet hours window (notifications suppressed after this time).')),
                ('quiet_hours_end', models.TimeField(default='08:00', help_text='End of quiet hours window (notifications resume after this time).')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this settings record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this settings record was last updated.')),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'team2_notification_setting',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='References the user in Core service. Not a FK (cross-service).')),
                ('title', models.CharField(help_text='Short descriptive title for the reminder.', max_length=255)),
                ('message', models.TextField(blank=True, default='', help_text='Optional body text for the reminder notification.')),
                ('reminder_time', models.TimeField(help_text='Time of day when the reminder should fire (HH:MM:SS).')),
                ('recurrence_pattern', models.CharField(choices=[('none', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', help_text='How often the reminder repeats.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this reminder is currently active and will fire.')),
                ('is_completed', models.BooleanField(default=False, help_text='Marked True when the user acknowledges the reminder.')),
                ('force_send_in_quiet_hours', models.BooleanField(default=False, help_text="If True, reminder fires even during the user's quiet hours.")),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. Reminders are never physically removed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this reminder was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this reminder was last updated.')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'db_table': 'team2_reminder',
                'ordering': ['reminder_time'],
                'indexes': [models.Index(fields=['user_id', 'is_deleted'], name='idx_reminder_user_active'), models.Index(fields=['user_id', 'is_completed'], name='idx_reminder_user_completed')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='Target user for this notification.')),
                ('title', models.CharField(help_text='Notification title as displayed to the user.', max_length=255)),
                ('message', models.TextField(blank=True, default='', help_text='Notification body text as displayed to the user.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current delivery status of this notification.', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Exact timestamp when the notification was successfully delivered.', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag (required by project standards).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this log entry was created.')),
                ('updated_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp of last status update.', null=True)),
                ('reminder', models.ForeignKey(blank=True, help_text='The reminder that triggered this notification (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='team2.reminder')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'team2_notification_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='idx_notif_log_user_status'), models.Index(fields=['user_id', '-created_at'], name='idx_notif_log_user_date')],
            },
        ),
    ]
