# Generated by Django 5.2.15 on 2026-07-23 15:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(choices=[('gym', 'Gym'), ('running', 'Running'), ('swimming', 'Swimming'), ('cycling', 'Cycling'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('crossfit', 'CrossFit'), ('home_workout', 'Home Workout')], max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('workout_type', models.CharField(choices=[('gym', 'Gym'), ('running', 'Running'), ('swimming', 'Swimming'), ('cycling', 'Cycling'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('crossfit', 'CrossFit'), ('home_workout', 'Home Workout')], db_index=True, max_length=30)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=20)),
                ('max_members', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_days', models.JSONField(default=list)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_groups', to='team6.fitnessgoal')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.CharField(max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_exercises', to='team6.exercise')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_exercises', to='team6.traininggroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_user_id', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('core_user_id__gt', 0)), name='team6_user_core_id_positive'), models.CheckConstraint(condition=models.Q(('age__gt', 0)), name='team6_user_age_positive'), models.CheckConstraint(condition=models.Q(('height__gt', 0)), name='team6_user_height_positive'), models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='team6_user_weight_positive')],
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_goals', to='team6.fitnessgoal')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_goals', to='team6.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=20)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analyses', to='team6.traininggroup')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analyses', to='team6.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InjuryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=150)),
                ('body_part', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('injury_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_history', to='team6.userprofile')),
            ],
            options={
                'ordering': ['-injury_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('left', 'Left'), ('rejected', 'Rejected')], db_index=True, default='active', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='team6.traininggroup')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='team6.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('gym', 'Gym'), ('running', 'Running'), ('swimming', 'Swimming'), ('cycling', 'Cycling'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('crossfit', 'CrossFit'), ('home_workout', 'Home Workout')], max_length=30)),
                ('available_days', models.JSONField(default=list)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('preferred_start_time', models.TimeField()),
                ('preferred_end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_preference', to='team6.userprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='traininggroup',
            constraint=models.CheckConstraint(condition=models.Q(('max_members__gt', 0)), name='team6_group_positive_capacity'),
        ),
        migrations.AddConstraint(
            model_name='traininggroup',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='team6_group_valid_time_range'),
        ),
        migrations.AddConstraint(
            model_name='groupexercise',
            constraint=models.UniqueConstraint(fields=('group', 'exercise'), name='team6_unique_group_exercise'),
        ),
        migrations.AddConstraint(
            model_name='usergoal',
            constraint=models.UniqueConstraint(fields=('user_profile', 'goal'), name='team6_unique_user_goal'),
        ),
        migrations.AddConstraint(
            model_name='riskanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='team6_risk_score_range'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('user_profile', 'group'), name='team6_unique_group_membership'),
        ),
        migrations.AddConstraint(
            model_name='workoutpreference',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_end_time__gt', models.F('preferred_start_time'))), name='team6_preference_valid_time_range'),
        ),
    ]
