# Generated by Django 5.2.15 on 2026-07-23 10:52

import django.core.validators
import django.db.models.deletion
import teams.team8.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('author_id', models.PositiveBigIntegerField(db_index=True)),
                ('author_username', models.CharField(max_length=150)),
                ('title', models.CharField(db_index=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('meals', models.JSONField(default=list, validators=[teams.team8.validators.validate_list])),
                ('is_published', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'diet_plans',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('author_id', models.PositiveBigIntegerField(db_index=True)),
                ('author_username', models.CharField(max_length=150)),
                ('title', models.CharField(db_index=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('weeks', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('exercises', models.JSONField(default=list, validators=[teams.team8.validators.validate_list])),
                ('is_published', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'training_plans',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='team8.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('author_id', models.PositiveBigIntegerField(db_index=True)),
                ('author_username', models.CharField(max_length=150)),
                ('title', models.CharField(db_index=True, max_length=240)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('content_type', models.CharField(choices=[('article', 'مقاله'), ('video', 'ویدیو'), ('training_plan', 'برنامه تمرینی'), ('diet_plan', 'برنامه رژیمی')], db_index=True, max_length=24)),
                ('body', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='content/%Y/%m/', validators=[teams.team8.validators.validate_video])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='content/thumbnails/%Y/%m/', validators=[teams.team8.validators.validate_image])),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('media_uploading', 'در حال بارگذاری'), ('ready', 'آماده انتشار'), ('published', 'منتشرشده'), ('archived', 'بایگانی\u200cشده'), ('rejected', 'ردشده')], db_index=True, default='draft', max_length=24)),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], db_index=True, default='beginner', max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='team8.category')),
            ],
            options={
                'db_table': 'contents',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='team8.content')),
            ],
            options={
                'db_table': 'content_ratings',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('author_id', models.PositiveBigIntegerField(db_index=True)),
                ('author_username', models.CharField(max_length=150)),
                ('title', models.CharField(db_index=True, max_length=240)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m/', validators=[teams.team8.validators.validate_image])),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], db_index=True, default='beginner', max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_free', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'بایگانی\u200cشده')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='team8.category')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('follower_id', models.PositiveBigIntegerField(db_index=True)),
                ('following_id', models.PositiveBigIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'follows',
                'indexes': [models.Index(fields=['following_id', '-created_at'], name='followers_idx'), models.Index(fields=['follower_id', '-created_at'], name='following_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower_id', 'following_id'), name='unique_follow_relationship'), models.CheckConstraint(condition=models.Q(('follower_id', models.F('following_id')), _negated=True), name='prevent_self_follow')],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=240)),
                ('order', models.PositiveSmallIntegerField()),
                ('body', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_lessons', to='team8.content')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='team8.course')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('active', 'ثبت\u200cنام\u200cشده'), ('in_progress', 'در حال یادگیری'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغوشده')], db_index=True, default='active', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='team8.course')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='team8.lesson')),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='team8.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='team8.lesson')),
            ],
            options={
                'db_table': 'lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('published', 'ارسال\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'outbox_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbox_pending_idx')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('author_id', models.PositiveBigIntegerField(db_index=True)),
                ('author_username', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=5000)),
                ('media', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/', validators=[teams.team8.validators.validate_image])),
                ('post_type', models.CharField(choices=[('general', 'عمومی'), ('workout', 'رکورد ورزشی'), ('progress', 'گزارش پیشرفت')], db_index=True, default='general', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('reported', 'گزارش\u200cشده'), ('hidden', 'مخفی')], db_index=True, default='published', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['author_id', 'status'], name='post_author_status_idx'), models.Index(fields=['status', '-published_at'], name='post_feed_idx'), models.Index(fields=['post_type', '-created_at'], name='post_type_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='team8.post')),
            ],
            options={
                'db_table': 'post_likes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('username', models.CharField(max_length=150)),
                ('text', models.TextField(max_length=1500)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='team8.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='team8.post')),
            ],
            options={
                'db_table': 'post_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('reporter_id', models.PositiveBigIntegerField(db_index=True)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('open', 'باز'), ('reviewed', 'بررسی\u200cشده'), ('dismissed', 'ردشده')], db_index=True, default='open', max_length=16)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='team8.post')),
            ],
            options={
                'db_table': 'post_reports',
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team8.course')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team8.tag')),
            ],
            options={
                'db_table': 'course_tags',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(related_name='courses', through='team8.CourseTag', to='team8.tag'),
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team8.content')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team8.tag')),
            ],
            options={
                'db_table': 'content_tags',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(related_name='contents', through='team8.ContentTag', to='team8.tag'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.PositiveBigIntegerField(unique=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('athlete', 'ورزشکار'), ('coach', 'مربی'), ('sports_doctor', 'پزشک ورزشی'), ('nutrition_specialist', 'متخصص تغذیه'), ('admin', 'مدیر')], db_index=True, default='athlete', max_length=32)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('specialization', models.CharField(blank=True, db_index=True, max_length=160)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', validators=[teams.team8.validators.validate_image])),
                ('location', models.CharField(blank=True, max_length=120)),
                ('experience_years', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(80)])),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['role', 'specialization'], name='profile_role_spec_idx'), models.Index(fields=['username', 'display_name'], name='profile_search_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('exercise_type', models.CharField(db_index=True, max_length=120)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('repetitions', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='team8.post')),
            ],
            options={
                'db_table': 'workout_records',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'name'], name='category_tree_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_sibling'),
        ),
        migrations.AddConstraint(
            model_name='contentrating',
            constraint=models.UniqueConstraint(fields=('content', 'user_id'), name='unique_content_rating'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='lesson_course_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_lesson_order'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user_id', 'status'], name='enrollment_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user_id', 'course'), name='unique_course_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson'), name='unique_lesson_progress'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user_id', '-created_at'], name='like_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('post', 'user_id'), name='unique_post_like'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent', 'created_at'], name='comment_thread_idx'),
        ),
        migrations.AddConstraint(
            model_name='postreport',
            constraint=models.UniqueConstraint(fields=('post', 'reporter_id'), name='unique_post_report'),
        ),
        migrations.AddConstraint(
            model_name='coursetag',
            constraint=models.UniqueConstraint(fields=('course', 'tag'), name='unique_course_tag'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_free'], name='course_available_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'difficulty'], name='course_filter_idx'),
        ),
        migrations.AddConstraint(
            model_name='contenttag',
            constraint=models.UniqueConstraint(fields=('content', 'tag'), name='unique_content_tag'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', 'content_type'], name='content_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['category', 'difficulty'], name='content_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['title', 'status'], name='content_title_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutrecord',
            index=models.Index(fields=['exercise_type', '-created_at'], name='workout_ex_date_idx'),
        ),
    ]
