# Generated by Django 5.2.15 on 2026-07-23 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='team8.content')),
            ],
            options={
                'db_table': 'content_views',
                'indexes': [models.Index(fields=['user_id', '-updated_at'], name='content_view_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('content', 'user_id'), name='unique_content_viewer')],
            },
        ),
    ]
