# Generated by Django 5.2.15 on 2026-07-24 08:05

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import teams.team8.models
import uuid
from django.db import migrations, models


def backfill_existing_paid_course_prices(apps, schema_editor):
    Course = apps.get_model("team8", "Course")
    Course._base_manager.filter(is_free=False, price=0).update(price=100000)


class Migration(migrations.Migration):

    dependencies = [
        ("team8", "0003_database_level_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_default=False,
                        db_index=True,
                        default=False,
                    ),
                ),
                ("user_id", models.PositiveBigIntegerField(db_index=True)),
            ],
            options={
                "db_table": "cart_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_default=False,
                        db_index=True,
                        default=False,
                    ),
                ),
                ("sender_id", models.PositiveBigIntegerField(db_index=True)),
                ("sender_username", models.CharField(max_length=150)),
                ("recipient_id", models.PositiveBigIntegerField(db_index=True)),
                ("recipient_username", models.CharField(max_length=150)),
                ("body", models.TextField(max_length=3000)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "direct_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_default=False,
                        db_index=True,
                        default=False,
                    ),
                ),
                ("user_id", models.PositiveBigIntegerField(db_index=True)),
                ("amount", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "پرداخت‌شده"),
                            ("refunded", "بازگشت وجه"),
                        ],
                        db_index=True,
                        default="completed",
                        max_length=16,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=teams.team8.models.purchase_reference,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
            ],
            options={
                "db_table": "purchases",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="قیمت دوره به تومان؛ برای دوره رایگان صفر است.",
            ),
        ),
        migrations.RunPython(
            backfill_existing_paid_course_prices,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_free", True), ("price", 0)),
                    models.Q(("is_free", False), ("price__gt", 0)),
                    _connector="OR",
                ),
                name="course_price_matches_free",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="team8.course",
            ),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["sender_id", "recipient_id", "-created_at"],
                name="direct_pair_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(
                fields=["recipient_id", "is_read", "-created_at"],
                name="direct_unread_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="directmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sender_id", models.F("recipient_id")),
                    _negated=True,
                ),
                name="prevent_self_message",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                to="team8.course",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("user_id", "course"),
                name="unique_user_cart_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                fields=("user_id", "course"),
                name="unique_user_course_purchase",
            ),
        ),
    ]
