
export const MOCK_GROUPS = [
  {
    id: 9001,
    name: "گروه صبحگاهی دویدن پارک ملت",
    goal: { name: "endurance" },
    workout_type: "running",
    difficulty_level: "intermediate",
    start_time: "06:30",
    end_time: "07:30",
    days: ["Saturday", "Monday", "Wednesday"],
    member_count: 7,
    max_members: 10,
    match_score: 92,
    risk: { level: "low" },
  },
  {
    id: 9002,
    name: "کراس‌فیت انرژی",
    goal: { name: "muscle_gain" },
    workout_type: "crossfit",
    difficulty_level: "advanced",
    start_time: "18:00",
    end_time: "19:30",
    days: ["Sunday", "Tuesday", "Thursday"],
    member_count: 12,
    max_members: 12,
    match_score: 74,
    risk: { level: "high" },
  },
  {
    id: 9003,
    name: "یوگا و آرامش",
    goal: { name: "flexibility" },
    workout_type: "yoga",
    difficulty_level: "beginner",
    start_time: "17:00",
    end_time: "18:00",
    days: ["Friday"],
    member_count: 4,
    max_members: 15,
    match_score: 88,
    risk: { level: "low" },
  },
];export default MOCK_GROUPS;